### ISSUE TITLE
If didn't call the Close method, the CPU% will never back low and always high, a

### ISSUE THREAD

**Issue by hizhao** [VoltDB/voltdb-client-go#21]
Hi, voltdb team. i found If didn't call the Close method, the CPU% will never back to low and always high, unless call Close method, but i don't want to call Close, because i wish the connection keepalive for other client to query. how to keep connection and get low %cpu?
(i tried ubunut 16.04 and osx 10.12, my env: voltdb 6.7, golang 1.7.3 )
my code:

func ExampleVoltDB() {
	conn, err := voltdbclient.OpenConn("localhost:21212")
	if err != nil {
		log.Fatal(err)
		os.Exit(-1)
	}
	//defer conn.Close() <-- i don't want to call Close, because i wish the connection keepalive for other client to query

	rows, err := conn.Query("@AdHoc", []driver.Value{"select * from user  LIMIT 100"})
	if err != nil {
		panic(err.Error())
	} else {
		voltRows := rows.(voltdbclient.VoltRows)
		for voltRows.AdvanceRow() {
			uid, err := voltRows.GetIntegerByName("uid")
			if err != nil {
				fmt.Println(err)
			}
			fmt.Println(uid)
		}
	}
}

func main() {
	ExampleVoltDB()
        //keep run about 3-5 mins, you'll found CPU fan starts spinning or run "top" command view cpu%
	log.Fatal(http.ListenAndServe(":8000", http.FileServer(http.Dir("./tmp"))))
}

**Comment by ppontryagin** [comment]
👍 similar issue

**Comment by gernest** [comment]
There is no sufficient information on this issue to investigate.

- missing database schema ( how can I reproduce?)
- the example is incomplete, and badly formatted.
- this falls on programming patterns.

You must declare the connection on top level if you wish for it to stick around.

I suggest you use this pattern when working with the client

```go
package main

import (
	"database/sql/driver"
	"fmt"
	"log"

	"github.com/VoltDB/voltdb-client-go/voltdbclient"
)

func main() {
	conn, err := voltdbclient.OpenConn("localhost:21212")
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()
	err = ExampleVoltDB(conn)
	if err != nil {
		log.Fatal(err)
	}
}

func ExampleVoltDB(conn *voltdbclient.Conn) error {
	rows, err := conn.Query("@AdHoc", []driver.Value{"select * from user  LIMIT 100"})
	if err != nil {
		return err
	}
	defer rows.Close()
	voltRows := rows.(voltdbclient.VoltRows)
	for voltRows.AdvanceRow() {
		uid, err := voltRows.GetIntegerByName("uid")
		if err != nil {
			return err
		}
		fmt.Println(uid)
	}

}
```

__PS__: You must always make sure `conn.Close` is called in order to release resources (sockets,goroutines, etc)

@abradley201 you can close this, it has nothing to do with the client, more to do with programming patterns using databases in Go.
