### ISSUE TITLE
Passing VoltTable as an argument to stored procedure

### ISSUE THREAD

**Issue by mroland91** [VoltDB/voltdb-client-go#60]
Hi,

Based on the documentation a stored procedure can accept these types as arguments:

Integer types | byte, short, int, long, Byte, Short, Integer, and Long
Floating point types | float, double, Float, Double
Fixed decimal types | BigDecimal
String and binary types | String and byte[]
Timestamp types | org.voltdb.types.TimestampType java.util.Date, java.sql.Date, java.sql.Timestamp
**VoltDB type | VoltTable**

The VoltTable type is unexported in this client so it cannot be used for stored procedure invocations.
Based on the code the encoder may not even handle this argument.

I'd be very grateful if You could share some information on this matter.

Thank You,
Best Regards,
Roland

**Comment by benjaminballard** [comment]
Hi Roland,

The wire protocol supports serialization for the basic data types for input parameters, plus VoltTable for results coming back from the database. Since the java client library uses some of the same code as the database, it can serialize a VoltTable to the byte code used by the wire protocol. Therefore, at some point it was decided to allow VoltTable to be supported as input to a stored procedure. It is very rarely used to my knowledge.

I'm not sure if any other client libraries support the creation of a VoltTable from code, and the serialization of a VoltTable onto the wire to be sent to the database as the parameter to a stored procedure invocation. Perhaps the python client can do it, I'm not certain. I think for most of the other client libraries, it's just not implemented.

Best regards,
Ben

**Comment by mroland91** [comment]
I understand, thank You, Ben!
